name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: paulhatch/semantic-version@v4.0.2
        id: semantic-version
        with:
          tag_prefix: "v"
          format: "3.8.1.${patch}-develop"
          short_tags: true
          bump_each_commit: true
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Restore dotnet tools
        run: dotnet tool restore
      - name: Run build.cake
        run: dotnet cake build.cake "--build-version=${{steps.semantic-version.outputs.version}}"
        env:
          GITHUB_ACTIONS: true
      - uses: actions/upload-artifact@main
        with:
          name: Nuget Packages ${{ matrix.os }}
          path: |
            Artifacts/**/*.nupkg
          if-no-files-found: error

